### ISSUE TITLE
World Select Placeholder

### ISSUE THREAD

**Issue by AngrySnorlax** [AngrySnorlax/TempleQuest#2]

**Comment by zfrick** [comment]
Yes im good at this

**Comment by richeynotdeferb** [comment]
not really

**Comment by zfrick** [comment]
Oh my Obama

**Comment by richeynotdeferb** [comment]
![bitch please im the definition of swag](https://cloud.githubusercontent.com/assets/13754079/9209462/aa2327a4-4044-11e5-9d9b-29b6d9a8f185.jpg)
